{"version":1,"defects":{"Warning":6,"Tests\\Unit\\RouterTest::it_registers_a_post_route":3,"Tests\\Unit\\RouterTest::there_are_no_routes_when_router_is_created":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception":4,"Error":4,"Tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":3,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_invoice_is_processed":3,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_email_when_invoice_processed":3},"times":{"Warning":0.223,"Tests\\Unit\\RouterTest::_it_registers_a_route":0.217,"Tests\\Unit\\RouterTest::test_that_it_registers_a_route":0.227,"Tests\\Unit\\RouterTest::it_registers_a_route":0.213,"Tests\\Unit\\RouterTest::it_registers_a_get_route":0,"Tests\\Unit\\RouterTest::it_registers_a_post_route":0,"Tests\\Unit\\RouterTest::there_are_no_routes_when_router_is_created":0.022,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception":0.027,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0.07,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0,"Error":0.013,"Tests\\Unit\\RouterTest::it_resolves_route_from_a_closure":0,"Tests\\Unit\\RouterTest::it_resolves_route":0,"Tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":0.794,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_invoice_is_processed":0.06,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_email_when_invoice_processed":0.055}}